[project]
name = "isocrypt"
version = "0.1.4"
description = ""
authors = [
    { name = "Poe Rhiza", email = "poerhiz@gmail.com" },
]
requires-python = ">=3.8"
classifiers = [
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    "typer==0.27.2",
    "humanfriendly==10.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pre-commit",
    "ruff",
    "mypy",
]

[project.scripts]
isocrypt = "isocrypt.main:app"

[build-system]
requires = ["setuptools>=81.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 131
target-version = "py38"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
]

[tool.ruff.lint.isort]
force-single-line = false
force-wrap-aliases = true
combine-as-imports = true
